# Generated by Django 2.2.5 on 2019-12-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seats', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
    ]
