# Generated by Django 2.2.5 on 2019-12-22 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
