# Generated by Django 2.2.5 on 2019-12-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_foods_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='date',
        ),
    ]
