# Generated by Django 2.2.7 on 2019-11-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketitems',
            old_name='foods',
            new_name='food',
        ),
    ]
